// <auto-generated />
using EntityFrameworkCore.CodeFirst.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore.CodeFirst.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCore.CodeFirst.Entities.Concrete.BasePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EntityFrameworkCore.CodeFirst.Entities.Concrete.Employee", b =>
                {
                    b.HasBaseType("EntityFrameworkCore.CodeFirst.Entities.Concrete.BasePerson");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("EntityFrameworkCore.CodeFirst.Entities.Concrete.Manager", b =>
                {
                    b.HasBaseType("EntityFrameworkCore.CodeFirst.Entities.Concrete.BasePerson");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("EntityFrameworkCore.CodeFirst.Entities.Concrete.Employee", b =>
                {
                    b.HasOne("EntityFrameworkCore.CodeFirst.Entities.Concrete.BasePerson", null)
                        .WithOne()
                        .HasForeignKey("EntityFrameworkCore.CodeFirst.Entities.Concrete.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkCore.CodeFirst.Entities.Concrete.Manager", b =>
                {
                    b.HasOne("EntityFrameworkCore.CodeFirst.Entities.Concrete.BasePerson", null)
                        .WithOne()
                        .HasForeignKey("EntityFrameworkCore.CodeFirst.Entities.Concrete.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
